[[constraint]]
  branch = "master"
  name = "github.com/dghubble/go-twitter"

[[constraint]]
  name = "github.com/dghubble/oauth1"
  version = "0.6.0"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/backoff"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/microerror"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/micrologger"

[[constraint]]
  name = "github.com/google/go-github"
  version = "v25.0.4"

[[constraint]]
  branch = "master"
  name = "github.com/the-anna-project/random"



[prune]
  go-tests = true
  unused-packages = true
